[tool.poetry]
name = "tbx"
version = "0.1.0"
description = "Torchbox.com"
authors = ["Torchbox Ltd"]

[tool.poetry.dependencies]
python = "^3.11"
Django = "~4.2"
wagtail = "~6.1"
psycopg2 = "^2.9.9"
gunicorn = {version = "^22.0.0", optional = true}
whitenoise = "^6.1.0"
phonenumbers = "^8.13.38"
Wand = "^0.6.10"

# Django packages
django-basic-auth-ip-whitelist = "^0.5"
django-birdbath = "^2.0.0"
django-csp = "^3.7"
django-pattern-library = "^1.1.0"
django-permissions-policy = "^4.15.0"
django-phonenumber-field = "^7.0.2"
django-redis = "^5.2.0"
django-referrer-policy = "~1.0"
django-storages = {version = "^1.14.3", extras = ["boto3"]}
dj-database-url = "^2.2.0"

# Wagtail packages
wagtail-accessibility = "^2.0.0"
wagtail-lite-youtube-embed = "^0.1.0"
wagtail-markdown = "^0.12.1"
wagtailmedia = {git = "https://github.com/torchbox-forks/wagtailmedia.git", rev="0.15.2+tbx"}
wagtail-purge = "^0.4.0"

# Production
scout-apm = "^3.1.0"
sentry-sdk = "^2.5.1"

[tool.poetry.extras]
gunicorn = ["gunicorn"]

[tool.poetry.dev-dependencies]
Werkzeug = "^2.1.2"
django-debug-toolbar = "^4.1.0"
django-extensions = "^3.2.1"
fabric = "^3.2.2"
pudb = "^2020.1"
honcho = "^1.1.0"

# Linters etc.
black = "^22.3.0"
detect-secrets = "^1.2.0"
djhtml = "^3.0.6"
flake8 = "^4.0.1"
isort = "^5.13.2"
pre-commit = "^2.19.0"
seed-isort-config = "^2.2.0"

# Documentation
mkdocs = "^1.5.3"
mkdocs-material = "^9.5.18"
pymdown-extensions = "^10.0.1"

# Testing
wagtail-factories = "^4.1.0"

[build-system]
requires = ["poetry>=1,<2"]
build-backend = "poetry.masonry.api"

[tool.black]
line_length = 88
target-version = ['py39']
exclude = '''
    /(
        .+/migrations
      | venv
      | \.venv
      | node_modules
      | \.git
    )/
'''
